version: '3.4'
services:
 npm_runner:
  image: system-npm_runner-prod:hot
  build:
   context: ../../
   dockerfile: ./docker/prod/npm_runner.Dockerfile
   cache_from:
    - system-npm_runner-prod:hot
 composer_runner:
  image: system-composer_runner-prod:hot
  build:
   context: ../..
   dockerfile: ./docker/prod/composer_runner.Dockerfile
   cache_from:
    - system-composer_runner-prod:hot
 app:
  image: system-app-prod:hot
  build:
   context: ../../
   dockerfile: ./docker/prod/app.Dockerfile
   cache_from:
    - system-app-prod:hot
 static:
  image: system-static-prod:hot
  build:
   context: ../../
   dockerfile: ./docker/prod/static.Dockerfile
   cache_from:
    - system-static-prod:hot
 proxy:
  image: system-proxy-prod:hot
  build:
   context: ../../
   dockerfile: ./docker/prod/proxy.Dockerfile
   cache_from:
    - system-proxy-prod:hot
